pipeline { 
  agent any 
  
  stages { 

    stage('Checkout') {
        steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/dallisonlima/jenkins-terraform']]])
          }
        }

    stage('Terraform Init') { 
      steps { 
        script { 
          dir("${env.WORKSPACE}/dev") { 
            sh 'terraform init' 
          } 
        } 
      } 
    } 
    
    stage('Terraform Plan') { 
      steps { 
        script { 
          dir("${env.WORKSPACE}/dev") { 
            sh 'terraform plan' 
          } 
        } 
      } 
    } 
    
    stage('Terraform Apply') { 
      steps { 
        script { 
          dir("${env.WORKSPACE}/dev") { 
            sh 'terraform apply' 
          } 
        } 
      } 
    } 
  } 
}