pipeline {
    agent any

    parameters {
        booleanParam(name: 'Apply', defaultValue: false, description: 'Automatically run apply after manual approval?')
        booleanParam(name: 'Destroy', defaultValue: false, description: 'Destroy Terraform build?')

    }


    stages {
        stage('Checkout') {
            steps {
            checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/dallisonlima/jenkins-terragrunt']]])            

          }
        }

        stage('Plan') {
            steps {
                dir('dev'){
                    sh 'ls -la'
                } 
            }

            steps {
                sh 'ls -la'
                sh 'terragrunt run-all plan'
            }

        }
    } 
}
